environments:
  fakescope: true
serialport: 
  name: "/dev/cu.usbserial-0001"
  timeout: 200
timezone: "Europe/Rome"
utc-offset: "-01.0"
geocoding:
  url: "https://geocoding.openapi.it/geocode"
  api_key: 
    production: "hujgovjqrb5capyn4ihrfvupplbmxj08"
    sandbox:
  token: "68e24742b455b3c8370ac1bf"
openngc:
  csv:
    path: "./openngc/csv/NGC.csv"
opendatasoft:
  url: "https://data.opendatasoft.com/api/explore/v2.1/catalog/datasets"
  messier-dataset: "ngc-ic-messier-catalog@datastro"
  hyg-dataset: "hyg-stellar-database@datastro"
hipparcos:
  csv:
    path: "./hipparcos/hipparcos2.csv"