environments:
  fakescope: true
serialport: "/dev/cu.usbserial-0001"
timezone: "Europe/Rome"
geocoding:
  url: "https://geocoding.openapi.it/geocode"
  api_key: 
    production: "nlwvf0vea4kdspgwquqneenegpdqeutm"
    sandbox:
  token: "662401dfa874ef890f0df052"
openngc:
  csv:
    path: "../openngc/csv/NGC.csv"
opendatasoft:
  url: "https://data.opendatasoft.com/api/explore/v2.1/catalog/datasets"
  messier-dataset: "ngc-ic-messier-catalog@datastro"
  hyg-dataset: "hyg-stellar-database@datastro"