environments:
  fakescope: true
serialport: 
  name: "/dev/cu.usbserial-0001"
  timeout: 500
timezone: "Europe/Rome"
utc-offset: "-01.0"
geocoding:
  url: "https://geocoding.openapi.it/geocode"
  api_key: 
    production: "hujgovjqrb5capyn4ihrfvupplbmxj08"
    sandbox:
  token: "68e24742b455b3c8370ac1bf"
openngc:
  csv:
    path: "../openngc/csv/NGC.csv"