environments:
  fakescope: true
serialport: 
  name: "/dev/cu.usbserial-0001"
  timeout: 500
timezone: "Europe/Rome"
utc-offset: "-01.0"
geocoding:
  url: "https://geocoding.openapi.it/geocode"
  api_key: 
    production: "nlwvf0vea4kdspgwquqneenegpdqeutm"
    sandbox:
  token: "662401dfa874ef890f0df052"
openngc:
  csv:
    path: "../openngc/csv/NGC.csv"