environments:
  fakescope: false
serialport: "/dev/cu.usbserial-0001"
geocoding:
  url: "https://geocoding.openapi.it/geocode"
  api_key: 
    production: "nlwvf0vea4kdspgwquqneenegpdqeutm"
    sandbox:
  token: "662401dfa874ef890f0df052"
openngc:
  csv:
    path: "./openngc/csv/NGC.csv"